export const bookData = {
  preface: {
    img: "/assets/svgs/content-chapter-svg/firstChapter.svg",
    imgWidth: 45,
    imgHeight: 51,
    title: "წინასიტყვაობა",
  },
  "qaosidan-kosmosamde": {
    img: "/assets/svgs/content-chapter-svg/secondChapter.svg",
    imgWidth: 50,
    imgHeight: 52,
    illustration: "/assets/svgs/generic/01_QaosidanCosmosamde.svg",
    audio: "/assets/mp3/qaosidan-kosmosamde.mp3",
    title: "ქაოსიდან კოსმოსამდე",
  },
  "yvelaze-seqsualuri-profesia": {
    img: "/assets/svgs/content-chapter-svg/thirdChapter.svg",
    imgWidth: 78,
    imgHeight: 49,
    illustration: "/assets/svgs/generic/02_KvelazeSeksualuriPropesia.svg",
    audio: "/assets/mp3/yvelaze-seqsualuri-profesia.mp3",
    title: "ყველაზე სექსუალური პროფესია",
  },
  jadoqari: {
    img: "/assets/svgs/content-chapter-svg/fourthChapter.svg",
    imgWidth: 45,
    imgHeight: 58,
    illustration: "/assets/svgs/generic/03_Jadokari.svg",
    audio: "/assets/mp3/jadoqari.mp3",
    title: "ჯადოქარი",
  },
  "shexvedra-leviatantan": {
    img: "/assets/svgs/content-chapter-svg/fifthChapter.svg",
    imgWidth: 49,
    imgHeight: 58,
    illustration: "/assets/svgs/generic/04_ShekhvedraLeviatantan.svg",
    audio: "/assets/mp3/shexvedra-leviatantan.mp3",
    title: "შეხვედრა ლევიათანთან",
  },
  "ofisebis-amaoeba": {
    img: "/assets/svgs/content-chapter-svg/sixthChapter.svg",
    imgWidth: 63,
    imgHeight: 49,
    illustration: "/assets/svgs/generic/05_OpisisAmaoeba.svg",
    audio: "/assets/mp3/ofisebis-amaoeba.mp3",
    title: "ოფისების ამაოება",
  },
  "xelovnuri-inteleqti": {
    img: "/assets/svgs/content-chapter-svg/seventhChapter.svg",
    imgWidth: 43,
    imgHeight: 64,
    illustration: "/assets/svgs/generic/06_CheshmaritiMastavlebeli.svg",
    audio: "/assets/mp3/xelovnuri-inteleqti.mp3",
    title: "ხელოვნური ინტელექტი",
  },
  "cheshmariti-maswavlebeli": {
    img: "/assets/svgs/content-chapter-svg/eighthChapter.svg",
    imgWidth: 48,
    imgHeight: 76,
    illustration: "/assets/svgs/generic/07_KhelovnuriIntelekti.svg",
    audio: "/assets/mp3/cheshmariti-maswavlebeli.mp3",
    title: "ჭეშმარიტი მასწავლებელი",
  },
  "shushis-qila": {
    img: "/assets/svgs/content-chapter-svg/ninthChapter.svg",
    imgWidth: 49,
    imgHeight: 60,
    illustration: "/assets/svgs/generic/08_ShushisKila.svg",
    audio: "/assets/mp3/shushis-qila.mp3",
    title: "შუშის ქილა",
  },
  "cifruli-samotxe": {
    img: "/assets/svgs/content-chapter-svg/tenthChapter.svg",
    imgWidth: 71,
    imgHeight: 43,
    illustration: "/assets/svgs/generic/09_TsipruliSamotkhe.svg",
    audio: "/assets/mp3/cifruli-samotxe.mp3",
    title: "ციფრული სამოთხე",
  },
  "naxatebit-saubari": {
    img: "/assets/svgs/content-chapter-svg/eleventhChapter.svg",
    imgWidth: 64,
    imgHeight: 44,
    illustration: "/assets/svgs/generic/10_NakhatebitSaubari.svg",
    audio: "/assets/mp3/naxatebit-saubari.mp3",
    title: "ნახატებით საუბარი",
  },
  ukvdaveba: {
    img: "/assets/svgs/content-chapter-svg/twelfthChapter.svg",
    imgWidth: 43,
    imgHeight: 68,
    illustration: "/assets/svgs/generic/11_Ukvdaveba.svg",
    audio: "/assets/mp3/ukvdaveba.mp3",
    title: "უკვდავება",
  },
};

export const books = Object.keys(bookData);
